- name: basic information
  hosts: all
  gather_facts: true
  become: true

  vars:
    cluster_admin: ubuntu
    admin_user:    ubuntu
    mail_domain:   "labo.local"     
    my_host:       "harbor"
    fqdn:          "{{ my_host }}.labo.local"
    my_data:       /harbor
    dst_dir:       /harbor/certs
    disk_sdc:      "{{ my_data }}"
    harbor_ver:    "v2.4.2"

  tasks:
  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  roles:
    - base_linux
    - mail-client    
    - docker
    - vdisks
    - download_certs

    
  tasks:
  #- debug: msg="{{ ansible_facts.enp0s9.ipv4.address }}"

  - name: Download the Harbor Installer
    shell: |
      gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys 644FF454C0B4115C
      curl -O -L https://github.com/goharbor/harbor/releases/download/{{ harbor_ver }}/harbor-online-installer-{{ harbor_ver }}.tgz
      curl -O -L https://github.com/goharbor/harbor/releases/download/{{ harbor_ver }}/harbor-online-installer-{{ harbor_ver }}.tgz.asc
      gpg -v –keyserver hkps://keyserver.ubuntu.com –verify harbor-online-installer-{{ harbor_ver }}.tgz.asc
      tar xzvf harbor-online-installer-{{ harbor_ver }}.tgz
    args:
      chdir: /harbor

  - name: Configure HTTPS Access to Harbor
    file:
      path: /harbor/certs
      state: directory

  #- get_url:
  #    url:  "https://{{ ca_ip }}/ca.pem"
  #    dest: /harbor/certs/harbor_internal_ca.crt
  #    validate_certs: no
  #    mode: 0440
  #
  #- get_url:
  #    url:  "https://{{ ca_ip }}/ca.key"
  #    dest: /harbor/certs/harbor_internal_ca.key
  #    validate_certs: no
  #    mode: 0440
  #
  #- name: Configure Internal TLS communication between Harbor Component
  #  shell: |
  #    docker run -v /:/hostfs goharbor/prepare:{{ harbor_ver }} gencert -p /harbor/certs
  #  args:
  #    chdir: /harbor/certs

  - name: copy harbor.yml
    template:
      src: harbor.yml.j2
      dest: /harbor/harbor/harbor.yml

  - name: Run the Installer Script
    shell: |
      ./install.sh
    args:
      chdir: /harbor/harbor

