- name: basic information
  hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  roles:
    - docker
    - vdisks
  tasks:
  #- debug: msg="{{ ansible_facts }}"
  #- debug: msg="{{ ansible_facts.enp0s9.ipv4.address }}"

  - name: Download the Harbor Installer
    shell: |
      gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys 644FF454C0B4115C
      curl -O -L https://github.com/goharbor/harbor/releases/download/v2.1.1/harbor-online-installer-v2.1.1.tgz
      curl -O -L https://github.com/goharbor/harbor/releases/download/v2.1.1/harbor-online-installer-v2.1.1.tgz.asc
      gpg -v –keyserver hkps://keyserver.ubuntu.com –verify harbor-online-installer-v2.1.1.tgz.asc
      tar xzvf harbor-online-installer-v2.1.1.tgz
    args:
      chdir: /harbor

  - name: Configure HTTPS Access to Harbor
    file:
      path: /harbor/certs
      state: directory

  - name: Create v3.ext
    template:
      src: v3.ext.j2
      dest: /harbor/certs/v3.ext
      
  - name: Configure HTTPS Access to Harbor
    shell: |
      openssl genrsa -out ca.key 4096
      openssl req -x509 -new -nodes -sha512 -days 3650 \
         -subj "/C=JP/ST=Tokyo/L=Tokyo/O=homelab/OU=homelab/CN=harbor.labs.local" \
         -key ca.key \
         -out ca.crt
      openssl genrsa -out harbor.labs.local.key 4096
      touch ~/.rnd
      openssl req -sha512 -new \
         -subj "/C=JP/ST=Tokyo/L=Tokyo/O=homelab/OU=homelab/CN=harbor.labs.local" \
         -key harbor.labs.local.key \
         -out harbor.labs.local.csr      
      openssl x509 -req -sha512 -days 3650 \
        -extfile v3.ext \
        -CA ca.crt -CAkey ca.key -CAcreateserial \
        -in harbor.labs.local.csr \
        -out harbor.labs.local.crt
      openssl x509 -inform PEM -in harbor.labs.local.crt -out harbor.labs.local.cert
      mkdir -p /etc/docker/certs.d/harbor.labs.local
      cp harbor.labs.local.cert /etc/docker/certs.d/harbor.labs.local
      cp harbor.labs.local.key /etc/docker/certs.d/harbor.labs.local
      cp ca.crt /etc/docker/certs.d/harbor.labs.local
      systemctl restart docker
    args:
      chdir: /harbor/certs

  - shell: |
      cp harbor.labs.local.cert /vagrant/harbor.labs.local.cert
      cp harbor.labs.local.key /vagrant/harbor.labs.local.key
      cp ca.crt /vagrant/ca.crt
    args:
      chdir: /harbor/certs
    when: ansible_facts.virtualization_type == "virtualbox"
      
  - name: Configure Internal TLS communication between Harbor Component
    shell: |
      cp ca.crt harbor_internal_ca.crt
      cp ca.key harbor_internal_ca.key
      docker run -v /:/hostfs goharbor/prepare:v2.1.0 gencert -p /harbor/certs
    args:
      chdir: /harbor/certs

      
  - name: copy harbor.yml
    template:
      src: harbor.yml.j2
      dest: /harbor/harbor/harbor.yml

  - name: Run the Installer Script
    shell: |
      ./install.sh
    args:
      chdir: /harbor/harbor
      
